### PR TITLE
Disables roundstart voting, and makes sleeper the default mode

### PR DESCRIPTION
**Pull request by improvedname**
For a calm RP experience 🙏

### CODE REVIEW

**Comment by PolymorphBlue** [comment]
I'm afraid I don't really like using the code to squash a config option - roundstart voting can be disabled via the config file, I believe.

As for the default storyteller, would you mind moving that into the config file as well?  I'm not sure we *want* a completely calm RP experience.

**Comment by king5327** [comment]
Does the storyteller even do anything? I don't think I've ever seen it do anything yet.

**Comment by DerFlammenwerfer** [comment]
> Does the storyteller even do anything? I don't think I've ever seen it do anything yet.

Not with random events disabled or on too low a population.

**Comment by improvedname** [comment]
@polymorphblue cant touch config files

**Comment by improvedname** [comment]
dead dreams

**Pull request closed without merging**
