### PR TITLE
Sanity + Some New Sojourn Stuff

### PR DESCRIPTION
**Pull request by APWill**
## About The Pull Request
Added the Eris sanity system along with various fixes for it that were implemented since then.

Also adds jelly blobs and jelly bloats.

## Changelog
**Mobs**
-Adds the hideous jelly blob, and the fatter and slower jelly bloat.

**Sanity**
-Added the sanity system. A full layout of how this system works can be found here (https://docs.google.com/document/d/1AG7ZsL0MQergzswM9vawFmjNIM3aaEBPVS_PcuohGOU/edit)
-Hotfix 1: Added spans to breakdown messages, and sanity checks - including one that prevents anchored items from being picked up.
-Hotfix 2: Halved volume of PTSD sound effects, and fixed obsession with upper body (which is impossible to acquire!)
-Hotfix 3: Added area sanity caching. Area sanity is now calculated once when an object with sanity bonus moves to or from an area instead of being calculated every Life tick for each mob.
-Hotfix 4: Fixes a a sanity-related runtime.
-Hotfix 5: Added global sanity damage modifier for easier balancing, currently set to 70%. Changed sanity view damage threshold from a define to a varibable, allowing to modify it per-character. Ghosts how have fabric images too.
-Hotfix 6: Allows all stats to be seen in the statistics tab until your sanity goes to 35 or under, at which your perception of your stats will appear to be randomly reduced, but not in reality.

### CODE REVIEW

**Comment by skraaak** [comment]
Disgusting, but works fine. Are these going to be added to the normal random hostile roster, or saved for the new map?

**Comment by APWill** [comment]
> Disgusting, but works fine. Are these going to be added to the normal random hostile roster, or saved for the new map?

I'm mainly bringing across new mobs for event use (poor Kazkin is VCing me at 2AM and crying down the mic because he's running out of new enemies for events) but I guess they could be ordinary map hostiles. It's fine either way.

Also I still need to do the actual Eris merge here, lazy lazy I'm so busy lately.

**Comment by DogZeroX** [comment]
_I'm already insane._

**Comment by APWill** [comment]
So this is merged but with three issues:
1. Genders don't show on examine.
2. Movement is slowed down to an absolute crawl.
3. Even with admin permissions I can't respawn when ghosting or playing in observer, getting the 'You must be dead to use this!' instead.

Basically this broke something hard.

**Comment by APWill** [comment]
Closing for now.

**Pull request closed without merging**
