### PR TITLE
Adds lawyer emotes

### PR DESCRIPTION
**Pull request by Snownbloodyflowers**
This is to familiarize myself with Eris code, cue the headbanging on wall.
## About The Pull Request
You are now able to roleplay to your content any lawyer shenanigans you may do. Aside from the lack of a gravel.

:cl:
- [x] "Objection!", has been added, containing both male and female voices are added
- [x] 'Authoritative' "Objection!" has been added, containing both male and female voices 
- [x] "Take that!" has been added, containing both male and female voices. 
- [x] "Hold it!" has been added, containing both male and female voices.
- [x] Add in a desk slam emote and sound
- [ ] Make it possible to break your hands from slamming on your desk
- [ ] Make a delay on using the emote to prevent spam.
- [ ] A whip has been added for whipping people who lack discipline. Captain or First Mate only.
- [ ] A riding crop has been added for trash item drop. Harmless, but can be used for ERP, -er discipline. 
- [ ] Special soundtrack added in when multiple people are in the courtroom.
- [ ] Fix the broken sound files.
/:cl:

### CODE REVIEW

**Comment by Snownbloodyflowers** [comment]
Ok tested. Following audio is broken for some reason.
Objection, female, male
Hold it female, male
Take that Male, female

**Comment by improvedname** [comment]
Dumb pr

**Comment by NopemanMcHalt** [comment]
Fix line ending on your end, please. This caused diff to get messed up.

**Comment by DogZeroX** [comment]
**OBJECTION!** _Throws a cheese_

**Pull request closed without merging**
