### PR TITLE
Perhaps adds more disks into game

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Adds 3 new disks 
Tools mods, has all tool mods
Lethal ammo box pack - has boxes of all lethal ammo
Non-Lethal ammo box pack - has all non-lethal ammo 
Adds in FS ultiument to the disk vender
Removes all coin items, added then to hack when 

## Why It's Good For The Game
At this time you can only really print/hope to fine ammo boxes so you end up printing 30 mags when dealing with roaches/hiveminds

Tools mods are easily made, or found in masses were cargo can just buy them for a small amount of sheckles 

Makes the vender folder a bit better as well by making them into lists rather then long lines

## Changelog
:cl:
add: Added new things
/:cl:

### CODE REVIEW

**Comment by Kazkin** [comment]
I like the ammo box generation for ammo but I don't like the tool mods being added to a generic disk that spawns automatically in engineer/tool storage/cargo. This also robs looting maintenance for tool mods and Aster's guild its choice to sell stuff.

I'd prefer tool mods being given their own custom disk at the same price a lethal ammo disk is (3000 credits) to maintain a semblance of game balance.

**Comment by Kazkin** [comment]
After more careful review and speaking with Trilby I'm convinced this PR should be approved, the disks for tool mods is expensive and has 3 uses according to Trilby. Since that was my only concern this has my approval.

**Comment by Trilbyspaceclone** [comment]
I cant fix it no matter what I do, its not even conflicting on my end

**Comment by Kazkin** [comment]
I think the reason it is conflicting is because your local fork's disks dm is different from the master disks dm.

**Comment by Kazkin** [comment]
Did... is it fully working now?

**Comment by Kazkin** [comment]
Huh, so it is working, glad I could help.
:^)

**Comment by APWill** [comment]
Thank you!

**Pull request merged**
