### PR TITLE
Basic cloaks with hood, plus department cloaks (without hoods)

### PR DESCRIPTION
**Pull request by NopemanMcHalt**
I'm sorry if mine obsession with cloaks may tire anyone.

:cl: Anonymous
add: Added black and ported red cloaks with hood from tgstation.
add: Ported department cloaks from CitRP, some sprites went under modifications. Go thank that moff for making me do this.
/:cl:

unknown unknown
dptcloak_preview
I forgot about GM one, so there is raw: 
image

Update: Changed MEO and Science cloaks a bit:
image
image

### CODE REVIEW

**Comment by DogZeroX** [comment]
I want one in red :3

**Comment by NopemanMcHalt** [comment]
@DogZeroX there you go fam

**Comment by DogZeroX** [comment]
@NopemanMcHalt Thanks :3

**Comment by NopemanMcHalt** [comment]
I think, I'm done here ¯\\_(ツ)_/¯

**Comment by DogZeroX** [comment]
*Dabs in downvote*

**Comment by DerFlammenwerfer** [comment]
No conflicts. If neck slot is added we can always edit the cloaks to go there.

**Pull request merged**
