### PR TITLE
(Waiting For Merge!) Big Clothing PR, even Hatter is impressed

### PR DESCRIPTION
**Pull request by APWill**
-A few clothing items are still missing, but I have people begging to have this merged now due to potential conflicts with their own upcoming PRs so oh well. Everything that's actually in here works fine.-

**CLOTHING UPDATES**
Hats:
14 beanies. [Added to beanie selection in loadout.]
Mulberry top hat. [Added to top hat selection in loadout.]
Basil bowler hat. [Added to bowler hat selection in loadout.]
Unarmored versions of the two detective fedoras. [Added to fedora selection in loadout.]
Ten cowboy hats - rancher, bandit, desperado, frontiersman, greenhorn, journeyman, longhorn, marshal, shootist, and wrangler. [Added to loadout.]
Six flower pins - blue, orange, pink, violet, white, and yellow. [Added to accessories category in loadout.]
sombrero [Added to hat category in loadout.]
Seven new welding helmets - aquatic, demon, technomancer, fancy, flame, ghetto, knight.
Animal costumes - carp hood, griffin head, ian hood, lobster head, bunny head.
Halloween costumes - scarecrow hat, pharaoh crown, skeleton head, death officer cap.
History costumes - street jester hat, court jester hat.
Job costumes - police cap.
Misc - elf hat, cueball helmet, electric cueball helmet.

Masks:
Animal masks - dolphin mask, frog mask, shark mask, rat mask, fox mask, bee mask, bear mask, bat mask, raven mask, jackal mask.
Halloween masks - demon mask, goblin mask, scarecrow sack, mummy bandages.
Misc masks - guy fawkes mask, happy tiki mask, startled tiki mask, confused tiki mask, angry tiki mask, gondola mask, rainbow clown mask.

Shoes:
Animal costumes - griffin boots.
History costumes - centurion sandals, knight boots, jester shoes.
pink shoes. [Added to shoe selection in loadout.]

Suits:
3 shirts. [Added to shirt selection in loadout.]
Kimono. [Added to suit category in loadout.]
Pink poncho. [Added to poncho selection in loadout.]
Animal costumes - carp suit, ian suit, bunny suit.
Halloween costumes - flash suit, mad scientist labcoat, pharaoh tunic, web bindings, skeleton costume, vampire coat.
Job costumes - imperium monk robe, sumo wrestler costume.
Kinky costumes - sexy engineer costume, sexy internal affairs costume, sexy lumberjack costume, sexy miner costume, sexy scientist costume.
Misc costumes - classic hacker costume, snowman suit, hastur robe.

Uniforms:
16 different colored jumpskirts. [Added to jumpskirt selection in loadout.]
Custom jumpskirt. [Added to uniform category in loadout.]
Rainbow jumpskirt.
Crimson suit, [Added to one-piece suit selection in loadout.]
Silver suit. [Added to one-piece suit selection in loadout.] (finally a use for vice officer's jumpsuit!)
Nudity permit. [Added to xenowear category in loadout.]
Burial garments.
Bathrobe.
Two types of gear harness. [Added to xenowear category in loadout.]
Medical gown.
Plaid green dress. [Added to dress selection in loadout.]
Loincloth. [Added to xenowear category in loadout.]
Animal costumes - griffin suit, lobster suit, owl suit.
Halloween costumes - nuclear survivor jumpsuit, death officer uniform, mummy wrappings, ragged pants, scarecrow rags, skeleton costume, vampire dress, villain suit.
History costumes - centurion armor, geisha dress, gladiator armor, street jester outfit, court jester outfit, napoleonic uniform, sailor garments.
Job costumes - blue clown suit, green clown suit, orange clown suit, purple clown suit, yellow clown suit, mail uniform, nurse dress, police uniform.
Kinky costumes - latex maid dress, leather gear, sexy mime outfit, green stripper outfit, pink stripper outfit.
Misc costumes - rainbow clown suit, gondola suit.

**OTHER STUFF**
-Rearranged action figures into different categories based on department. Keep an eye on new 'discontinued' figures based on unused jobs (i.e. mime).
-Moved undercloaks into the xenowear category and fixed the naming, many were called 'undercoats'.
-Many new plushies, from carps to foxes to therapy dolls.
-Other new toys: stick horse, eight ball, conch shell, mini xmas tree.
-Added some new decals and signs like wall clocks. Not as major as the last PR I made since I got most stuff then, but there's a bit more in here.
-Fixed the irritating 'wais' typo.

### CODE REVIEW

**Comment by StellarTheAwoo** [comment]
I'm confused as to why you are still getting a difference even though you did some things to attempt to pull it through, but I suppose it could be chocked up to an issue with the bot.

**Comment by Hatterhat** [comment]
kinda cringe tbh

**Comment by APWill** [comment]
> I'm confused as to why you are still getting a difference even though you did some things to attempt to pull it through, but I suppose it could be chocked up to an issue with the bot.

As discussed in Discord it's the  _"The table 'IconDiffs' is full"_ error which, yes, is just down to the bot being screwy. Nothing wrong with this PR, at least from that standpoint. : P

**Comment by PolymorphBlue** [comment]
Question - why was some of the flavour text removed / simplified from some uniforms?

**Comment by APWill** [comment]
> Question - why was some of the flavour text removed / simplified from some uniforms?

1. Some of the descriptions are a bit messy and overblown. It would be cool if they all fit onto a single line of text to reduce the clutter when you examine something too.

2. The memes! Look at the chicken suit... "made long ago by the ancient empire KFC."  It's funny but people get confused and think this stuff has real lore implications. xP

I need to actually go through a lot of the descriptions still, it's just boring and I need to organise the clothing folders first and I wanna focus on content right now.

**Pull request merged**
