### PR TITLE
Dueltiders, a yugioh ss13 themed cardgame

### PR DESCRIPTION
**Pull request by improvedname**
To do

- [ ]  More cards to be added

- [ ] Preset Decks

- [ ] The auctall mechanics

- [x] A towel to clean my tears with

### CODE REVIEW

**Comment by DogZeroX** [comment]
Fucking gay.

**Comment by Kazkin** [comment]
Nah fam.

**Comment by Kazkin** [comment]
This one is safe to deny.

**Comment by APWill** [comment]
Closing because it's even more abandoned than Dino Crisis.

Feel free to resubmit if you're gonna finish it. ; )

**Pull request closed without merging**
