### PR TITLE
Adds gas masks to loadouts for 2 points

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Masked cat

### CODE REVIEW

**Comment by DogZeroX** [comment]
*powergaming reeee (?)*

**Comment by improvedname** [comment]
👎

**Comment by APWill** [comment]
PR Review Team think this is a great addition and I feel bad for not putting it onto the loadout menu myself. Maybe for only 1 point though? Our new map will make them not so useful and with only 10 points, 3 is a pretty high price to pay for something you can find in any O2 locker.

**Comment by improvedname** [comment]
@APWill Gas masks will always be usefull they defy smoke based chems

**Pull request merged**
