### PR TITLE
allows you to copy character slots to another slot

### PR DESCRIPTION
**Pull request by improvedname**
Adds the ability to select a slot, and copy it to another character slot, for minor edits to the same character or anything

### CODE REVIEW

**Comment by king5327** [comment]
I'm gonna need opinions on this. On the one hand it allows for variants of a species to be made easily. On the other, it invites making clones of your characters to bypass knowledge restrictions that'll be implemented later. Personally, I'm for this since it's quality of life, but you never know.

**Comment by improvedname** [comment]
Just make knowledge a slot spefific thing, vore handls it in the same way

**Comment by PolymorphBlue** [comment]
My opinion is merge it.

**Comment by APWill** [comment]
Yes it can be abused, but you could say that about a lot of systems on the server.

It's a great addition which is VERY convenient. Yes, merge!

**Pull request merged**
