### PR TITLE
Various Additions

### PR DESCRIPTION
**Pull request by APWill**
## About The Pull Request
Some nice changes that aren't actually just the result of merging things for once. Mainly stuff that doesn't fit Eris or is a bit irrelevant for it, but is good for the more HRP-focused Sojourn environment.

## Changelog
**Posters**
-Adds 62 new posters. All posters (including the old ones too) now have unique file paths so they can be spawned individually without having to bother with var editing. [It took a while.]
**Closets**
-Added blue wardrobe and red wardrobe. These have also been added to the random wardrobe pool so you should see these appear in-game.
-All colored wardrobes now contain a appropriately colored jumpskirt. More appropriately colored items have been added to them too, including bandanas and caps where available.
**Hospitality Crates**
-Moved Lunchbox Crate from Operations to Hospitality, and Kitchen Supply Crate from Supply to Hospitality, to bring all food-related items together.
-Added burger surprise crate. Contains 5 random burgers.
-Added cake surprise crate. Contains 2 random sliceable cakes.
**Operations Crates**
-Moved Toner Cartridges Crate from Supply to Operations.
-Moved Janitorial Supplies Crate from Supply to Operations.
**Items**
-Added gavel hammer and gavel block. One of each is now present in the courtroom.
**Mobs**
-Five new simple animal mobs - red panda, fae panda, penguin, goose, and fennec.
-One red panda appears to have snuck aboard, can you find them?
-Gave the clown mob a more detailed description, and more voice lines. Fixed a bug where they couldn't speak before!
**Vending Machines**
New vending machine slogans from Papalus.

### CODE REVIEW

**Comment by LordPapalus** [comment]
Looks good to me

**Comment by Kazkin** [comment]
I reviewed this earlier, good to go.

**Comment by skraaak** [comment]
Seeing as you've tested it and everything seems in order by the looks of it, I'd say it's good to go.

**Comment by APWill** [comment]
thx xxx

**Pull request merged**
