### PR TITLE
Merges Eris master to now

### PR DESCRIPTION
**Pull request by PolymorphBlue**
Leaves the map, though, as their current  version isn't usable.

### CODE REVIEW

**Comment by DogZeroX** [comment]
Weh

**Comment by DogZeroX** [comment]
I feel like this will break a lot of things...

**Comment by PolymorphBlue** [comment]
I mean, it only broke one thing I saw in my 10 minutes of testing?  (But Eris master had it broken too)

**Comment by DogZeroX** [comment]
I mean like. Combining our modified code with the update, it will likely break and cause conflicts.

**Comment by APWill** [comment]
> I mean like. Combining our modified code with the update, it will likely break and cause conflicts.

Download the polymorphblue branch and try it for yourself - our code merged with all of the Eris commits here is working just fine.

There's one or two little edits to make (I notice some entries are duplicated on the loadout for example) but mechanically this is totally fine and I'm seeing no issues when playtesting.

**Pull request merged**
