### PR TITLE
grammar tweak, nonantag excel disk

### PR DESCRIPTION
**Pull request by Hatterhat**
no implant reconstructor = no converts

### CODE REVIEW

**Comment by improvedname** [comment]
But without implant half of this shit shall kill you anyways

**Comment by Hatterhat** [comment]
a valuable lesson to be learned for anyone who builds the things that will kill them while not excel

**Comment by Kazkin** [comment]
Looks good to me.

**Comment by APWill** [comment]
Approved. Thank you!

**Pull request merged**
