### PR TITLE
Adds cloning machines to medbay

### PR DESCRIPTION
**Pull request by Delnth**
Adds a cloning pod, console and dna scanner/modifier for cloning purposes, as well as a diskette box (which I hope contains cloning data disks) and a patient closet.

### CODE REVIEW

**Comment by DerFlammenwerfer** [comment]
Your map fails to compile with 13 errors, some of them pertaining to synthetic flashes and others being type unknown errors.

**Comment by DerFlammenwerfer** [comment]
Labling as a DNR for now, k5 still needs to fix the compiling errors.

**Comment by king5327** [comment]
It literally compiles though. The issue here is that I can't guarantee the cloning process itself actually clones faithfully.

**Comment by DerFlammenwerfer** [comment]
We will be removing cloning entirely, and instead be adding reconstructive surgery and reworked defibrillation.

**Pull request closed without merging**
